--------------------------------------------------------
--  Fichier créé - mardi-mars-07-2023   
--------------------------------------------------------
DROP TABLE "SYSTEM"."DONATEUR";
--------------------------------------------------------
--  DDL for Table DONATEUR
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."DONATEUR" 
   (	"ID_DONATEUR" NUMBER, 
	"NOM" VARCHAR2(50 BYTE), 
	"PRENOM" VARCHAR2(50 BYTE), 
	"ADDRESSE" VARCHAR2(50 BYTE), 
	"NUM_TEL" NUMBER, 
	"EMAIL" VARCHAR2(50 BYTE), 
	"TYPE_DONATEUR" VARCHAR2(50 BYTE), 
	"NB_DON" NUMBER, 
	"QUANTITE" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.DONATEUR
SET DEFINE OFF;
Insert into SYSTEM.DONATEUR (ID_DONATEUR,NOM,PRENOM,ADDRESSE,NUM_TEL,EMAIL,TYPE_DONATEUR,NB_DON,QUANTITE) values ('4','bouaziz','titta','esprit','22222','maram@esprit.com','societe','2','2');
Insert into SYSTEM.DONATEUR (ID_DONATEUR,NOM,PRENOM,ADDRESSE,NUM_TEL,EMAIL,TYPE_DONATEUR,NB_DON,QUANTITE) values ('6','bachta','akrem','ezzahra','5625565','akrem@esprit.com','societe','2','2');
--------------------------------------------------------
--  DDL for Index DONATEUR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."DONATEUR_PK" ON "SYSTEM"."DONATEUR" ("ID_DONATEUR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table DONATEUR
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."DONATEUR" ADD CONSTRAINT "DONATEUR_PK" PRIMARY KEY ("ID_DONATEUR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."DONATEUR" MODIFY ("QUANTITE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."DONATEUR" MODIFY ("NB_DON" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."DONATEUR" MODIFY ("TYPE_DONATEUR" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."DONATEUR" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."DONATEUR" MODIFY ("NUM_TEL" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."DONATEUR" MODIFY ("ADDRESSE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."DONATEUR" MODIFY ("PRENOM" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."DONATEUR" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."DONATEUR" MODIFY ("ID_DONATEUR" NOT NULL ENABLE);
