--------------------------------------------------------
--  Fichier créé - mardi-mars-07-2023   
--------------------------------------------------------
DROP TABLE "SYSTEM"."DONATAIRES";
--------------------------------------------------------
--  DDL for Table DONATAIRES
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."DONATAIRES" 
   (	"ID_DONATAIRE" NUMBER, 
	"TYPE_DE_DON" VARCHAR2(100 BYTE), 
	"NUM_TEL" NUMBER, 
	"QUANTITE_DE_DON" NUMBER, 
	"NOM" VARCHAR2(100 BYTE), 
	"BESOIN" VARCHAR2(100 BYTE), 
	"ADRESSE" VARCHAR2(100 BYTE), 
	"DATE_DE_DON" NUMBER, 
	"TYPE_DONATAIRE" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into RAOUF.DONATAIRES
SET DEFINE OFF;
Insert into SYSTEM.DONATAIRES (ID_DONATAIRE,TYPE_DE_DON,NUM_TEL,QUANTITE_DE_DON,NOM,BESOIN,ADRESSE,DATE_DE_DON,TYPE_DONATAIRE) values ('1',null,'0','0','amir',null,null,'0',null);
--------------------------------------------------------
--  DDL for Index DONATAIRES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."DONATAIRES_PK" ON "SYSTEM"."DONATAIRES" ("ID_DONATAIRE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table DONATAIRES
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."DONATAIRES" ADD CONSTRAINT "DONATAIRES_PK" PRIMARY KEY ("ID_DONATAIRE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."DONATAIRES" MODIFY ("ID_DONATAIRE" NOT NULL ENABLE);
