--------------------------------------------------------
--  File created - Tuesday-March-07-2023   
--------------------------------------------------------
DROP TABLE "SYSTEM"."GESTION_EMPLOYER";
--------------------------------------------------------
--  DDL for Table GESTION_EMPLOYER
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."GESTION_EMPLOYER" 
   (	"NOM" VARCHAR2(20 BYTE), 
	"FONCTION" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(20 BYTE), 
	"ID" NUMBER(*,0), 
	"STATUT" VARCHAR2(20 BYTE), 
	"NUM_TEL" NUMBER, 
	"ADRESSE" VARCHAR2(20 BYTE), 
	"MDP" VARCHAR2(20 BYTE), 
	"DROIT_ACCESS" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into AKREM.GESTION_EMPLOYER
SET DEFINE OFF;
Insert into SYSTEM.GESTION_EMPLOYER (NOM,FONCTION,EMAIL,ID,STATUT,NUM_TEL,ADRESSE,MDP,DROIT_ACCESS) values ('akrem','efsaaef','fdasfasefas',1,'aesfsef',0,'esafase','sefasf','aefsf');
--------------------------------------------------------
--  DDL for Index GESTION_EMPLOYER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."GESTION_EMPLOYER_PK" ON "SYSTEM"."GESTION_EMPLOYER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table GESTION_EMPLOYER
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."GESTION_EMPLOYER" ADD CONSTRAINT "GESTION_EMPLOYER_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."GESTION_EMPLOYER" MODIFY ("DROIT_ACCESS" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."GESTION_EMPLOYER" MODIFY ("MDP" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."GESTION_EMPLOYER" MODIFY ("ADRESSE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."GESTION_EMPLOYER" MODIFY ("NUM_TEL" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."GESTION_EMPLOYER" MODIFY ("STATUT" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."GESTION_EMPLOYER" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."GESTION_EMPLOYER" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."GESTION_EMPLOYER" MODIFY ("FONCTION" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."GESTION_EMPLOYER" MODIFY ("NOM" NOT NULL ENABLE);
