--------------------------------------------------------
--  Fichier créé - mardi-mars-07-2023   
--------------------------------------------------------
DROP TABLE "SYSTEM"."GESTION_STOCK";
--------------------------------------------------------
--  DDL for Table GESTION_STOCK
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."GESTION_STOCK" 
   (	"ID_ALIMENT" NUMBER, 
	"QUANTITE" NUMBER, 
	"DATE_EXP" DATE, 
	"DATE_REC" DATE, 
	"LIEU_REC" VARCHAR2(20 BYTE), 
	"REF" VARCHAR2(20 BYTE), 
	"DATE_DEST" DATE, 
	"DEST" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.GESTION_STOCK
SET DEFINE OFF;
Insert into SYSTEM.GESTION_STOCK (ID_ALIMENT,QUANTITE,DATE_EXP,DATE_REC,LIEU_REC,REF,DATE_DEST,DEST) values ('13','1',to_date('09/11/02','DD/MM/RR'),to_date('19/09/02','DD/MM/RR'),'MARAM','non',to_date('15/02/21','DD/MM/RR'),'KOUKOU');
Insert into SYSTEM.GESTION_STOCK (ID_ALIMENT,QUANTITE,DATE_EXP,DATE_REC,LIEU_REC,REF,DATE_DEST,DEST) values ('16','100',to_date('01/01/38','DD/MM/RR'),to_date('01/01/29','DD/MM/RR'),'TUNISIE','non',to_date('01/01/26','DD/MM/RR'),'TITTA');
Insert into SYSTEM.GESTION_STOCK (ID_ALIMENT,QUANTITE,DATE_EXP,DATE_REC,LIEU_REC,REF,DATE_DEST,DEST) values ('14','200',to_date('01/01/24','DD/MM/RR'),to_date('01/01/29','DD/MM/RR'),'TUNISIE','non',to_date('01/01/24','DD/MM/RR'),'maram');
--------------------------------------------------------
--  DDL for Index GESTION_STOCK_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."GESTION_STOCK_PK" ON "SYSTEM"."GESTION_STOCK" ("ID_ALIMENT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table GESTION_STOCK
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."GESTION_STOCK" ADD CONSTRAINT "GESTION_STOCK_PK" PRIMARY KEY ("ID_ALIMENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."GESTION_STOCK" MODIFY ("ID_ALIMENT" NOT NULL ENABLE);
